<!--yml
category: 未分类
date: 0001-01-01 00:00:00
-->

# JAVA 语言如何进行异常处理，关键字：throws,throw,try,catch,finally分别代表什么意义在 try 块中可以抛出异常吗

> 原文：[https://zwmst.com/2439.html](https://zwmst.com/2439.html)

   [ *Java基础* ](https://zwmst.com/java%e5%9f%ba%e7%a1%80)*[ <time datetime="2021-08-25T09:34:43+08:00"> 2021-08-25 </time> ](https://zwmst.com/2439.html)  答：Java 通过面向对象的方法进行异常处理，把各种不同的异常进行分类，并提供了良好的接口。
在 Java 中，每个异常都是一个对象，它是 Throwable 类或其它子类的实例。
当一个方法出现异常后便抛出一个异常对象，该对象中包含有异常信息，调用这个对象的方法可以捕获到这个异常并进行处理。
Java 的异常处理是通过 5 个关键词来实现的：**try、catch、throw、throws 和 finally。** 一般情况下是用 try 来执行一段程序，如果出现异常，系统会抛出（throws）一个异常，这时候你可以通过它的类型来捕捉（catch）它，或最后（finally）由缺省处理器来处理；

*   try 用来指定一块预防所有“异常”的程序；
*   catch 子句紧跟在 try 块后面，用来指定你想要捕捉的“异常”的类型；
*   throw 语句用来明确地抛出一个“异常”；
*   throws 用来标明一个成员函数可能抛出的各种“异常”；
*   Finally 为确保一段代码不管发生什么“异常”都被执行一段代码；

    可以在一个成员函数调用的外面写一个 try 语句，在这个成员函数内部写另一个 try 语句保护其他代码。
    每当遇到一个 try 语句，“异常”的框架就放到堆栈上面，直到所有的 try 语句都完成。
    如果下一级的 try 语句没有对某种“异常”进行处理，堆栈就会展开，直到遇到有处理这种“异常”的 try 语句。*